recipe_list:
    path:     /
    defaults: { _controller: RecipeBundle:Recipe:list }

recipe_create:
    path:     /create
    defaults: { _controller: RecipeBundle:Recipe:create }

recipe_details:
    path:     /details/{id}
    defaults: { _controller: RecipeBundle:Recipe:details }

recipe_edit:
    path:     /edit/{id}
    defaults: { _controller: RecipeBundle:Recipe:edit }

recipe_delete:
    path:     /delete/{id}
    defaults: { _controller: RecipeBundle:Recipe:delete }